### ISSUE TITLE
refactoring of FCM messaging (front backend integration)

### ISSUE THREAD

**Issue by duduyiq2001** [duduyiq2001/centero#9]
currently all messages sent from backend fcm are strings, it's hard for client side to parse that and interpret what they are for.
Currently all messages get handled by the same handler at the frontend.
refactoring needs to be done so that backend sends json
{ 
 message: json.stringify({message: ..., alerttype: ...
)
}
frontend parse the json data and pass it off to different handlers that triggers different actions based on the alerttype(when user cancels call before manager accept vs user ends call during call)

**Comment by TimTwigg** [comment]
I think this is already done, see `functions/src/index.ts:64` and `lib/controllers/authentication/residentauthentication.dart:57` (line numbers are for "tim" branch, might be different on other branches).

**Comment by duduyiq2001** [comment]
fixed
